=== UniversalViewer/universalviewer/dist/uv-1.5.2/schema/uv-seadragon-extension.en-GB.schema.json
{"$schema":"http://json-schema.org/draft-04/schema#","description":"","type":"object","properties":{"options":{"type":"object","properties":{"leftPanelEnabled":{"type":"boolean"},"minWidthBreakPoint":{"type":"number"},"overrideFullScreen":{"type":"boolean"},"pagingEnabled":{"type":"boolean"},"pessimisticAccessControl":{"type":"boolean"},"preserveViewport":{"type":"boolean"},"rightPanelEnabled":{"type":"boolean"},"searchWithinEnabled":{"type":"boolean"},"theme":{"type":"string","minLength":1}},"required":["leftPanelEnabled","minWidthBreakPoint","overrideFullScreen","pagingEnabled","pessimisticAccessControl","preserveViewport","rightPanelEnabled","searchWithinEnabled","theme"]},"modules":{"type":"object","properties":{"dialogue":{"type":"object","properties":{"content":{"type":"object","properties":{"close":{"type":"string","minLength":1}},"required":["close"]}},"required":["content"]},"downloadDialogue":{"type":"object","properties":{"options":{"type":"object","properties":{"confinedImageSize":{"type":"number"}},"required":["confinedImageSize"]},"content":{"type":"object","properties":{"currentViewAsJpg":{"type":"string","minLength":1},"download":{"type":"string","minLength":1},"editSettings":{"type":"string","minLength":1},"entireDocument":{"type":"string","minLength":1},"entireFileAsOriginal":{"type":"string","minLength":1},"noneAvailable":{"type":"string","minLength":1},"pagingNote":{"type":"string","minLength":1},"preview":{"type":"string","minLength":1},"title":{"type":"string","minLength":1},"wholeImageHighRes":{"type":"string","minLength":1},"wholeImageLowResAsJpg":{"type":"string","minLength":1}},"required":["currentViewAsJpg","download","editSettings","entireDocument","entireFileAsOriginal","noneAvailable","pagingNote","preview","title","wholeImageHighRes","wholeImageLowResAsJpg"]}},"required":["options","content"]},"embedDialogue":{"type":"object","properties":{"options":{"type":"object","properties":{"embedTemplate":{"type":"string","minLength":1}},"required":["embedTemplate"]},"content":{"type":"object","properties":{"customSize":{"type":"string","minLength":1},"height":{"type":"string","minLength":1},"instructions":{"type":"string","minLength":1},"title":{"type":"string","minLength":1},"width":{"type":"string","minLength":1}},"required":["customSize","height","instructions","title","width"]}},"required":["options","content"]},"footerPanel":{"type":"object","properties":{"options":{"type":"object","properties":{"downloadEnabled":{"type":"boolean"},"embedEnabled":{"type":"boolean"},"fullscreenEnabled":{"type":"boolean"},"minimiseButtons":{"type":"boolean"}},"required":["downloadEnabled","embedEnabled","fullscreenEnabled","minimiseButtons"]},"content":{"type":"object","properties":{"download":{"type":"string","minLength":1},"embed":{"type":"string","minLength":1},"exitFullScreen":{"type":"string","minLength":1},"fullScreen":{"type":"string","minLength":1}},"required":["download","embed","exitFullScreen","fullScreen"]}},"required":["options","content"]},"genericDialogue":{"type":"object","properties":{"content":{"type":"object","properties":{"emptyValue":{"type":"string","minLength":1},"invalidNumber":{"type":"string","minLength":1},"noMatches":{"type":"string","minLength":1},"ok":{"type":"string","minLength":1},"pageNotFound":{"type":"string","minLength":1},"refresh":{"type":"string","minLength":1}},"required":["emptyValue","invalidNumber","noMatches","ok","pageNotFound","refresh"]}},"required":["content"]},"helpDialogue":{"type":"object","properties":{"content":{"type":"object","properties":{"text":{"type":"string","minLength":1},"title":{"type":"string","minLength":1}},"required":["text","title"]}},"required":["content"]},"moreInfoRightPanel":{"type":"object","properties":{"options":{"type":"object","properties":{"panelAnimationDuration":{"type":"number"},"panelCollapsedWidth":{"type":"number"},"panelExpandedWidth":{"type":"number"},"panelOpen":{"type":"boolean"},"textLimit":{"type":"number"},"textLimitType":{"type":"string","minLength":1}},"required":["panelAnimationDuration","panelCollapsedWidth","panelExpandedWidth","panelOpen","textLimit","textLimitType"]},"content":{"type":"object","properties":{"collapse":{"type":"string","minLength":1},"collapseFull":{"type":"string","minLength":1},"expand":{"type":"string","minLength":1},"expandFull":{"type":"string","minLength":1},"holdingText":{"type":"string","minLength":1},"less":{"type":"string","minLength":1},"more":{"type":"string","minLength":1},"noData":{"type":"string","minLength":1},"title":{"type":"string","minLength":1}},"required":["collapse","collapseFull","expand","expandFull","holdingText","less","more","noData","title"]}},"required":["options","content"]},"pagingHeaderPanel":{"type":"object","properties":{"options":{"type":"object","properties":{"localeToggleEnabled":{"type":"boolean"},"pageModeEnabled":{"type":"boolean"},"pagingToggleEnabled":{"type":"boolean"}},"required":["localeToggleEnabled","pageModeEnabled","pagingToggleEnabled"]},"content":{"type":"object","properties":{"close":{"type":"string","minLength":1},"emptyValue":{"type":"string","minLength":1},"first":{"type":"string","minLength":1},"firstImage":{"type":"string","minLength":1},"firstPage":{"type":"string","minLength":1},"folio":{"type":"string","minLength":1},"go":{"type":"string","minLength":1},"help":{"type":"string","minLength":1},"image":{"type":"string","minLength":1},"last":{"type":"string","minLength":1},"lastImage":{"type":"string","minLength":1},"lastPage":{"type":"string","minLength":1},"next":{"type":"string","minLength":1},"nextImage":{"type":"string","minLength":1},"nextPage":{"type":"string","minLength":1},"of":{"type":"string","minLength":1},"oneUp":{"type":"string","minLength":1},"page":{"type":"string","minLength":1},"previous":{"type":"string","minLength":1},"previousImage":{"type":"string","minLength":1},"previousPage":{"type":"string","minLength":1},"settings":{"type":"string","minLength":1},"twoUp":{"type":"string","minLength":1}},"required":["close","emptyValue","first","firstImage","firstPage","folio","go","help","image","last","lastImage","lastPage","next","nextImage","nextPage","of","oneUp","page","previous","previousImage","previousPage","settings","twoUp"]}},"required":["options","content"]},"seadragonCenterPanel":{"type":"object","properties":{"options":{"type":"object","properties":{"controlsFadeAfterInactive":{"type":"number"},"controlsFadeDelay":{"type":"number"},"controlsFadeLength":{"type":"number"},"defaultZoomLevel":{"type":"number"},"navigatorPosition":{"type":"string","minLength":1},"pageGap":{"type":"number"},"trimAttributionCount":{"type":"number"}},"required":["controlsFadeAfterInactive","controlsFadeDelay","controlsFadeLength","defaultZoomLevel","navigatorPosition","pageGap","trimAttributionCount"]},"content":{"type":"object","properties":{"acknowledgements":{"type":"string","minLength":1},"goHome":{"type":"string","minLength":1},"imageUnavailable":{"type":"string","minLength":1},"next":{"type":"string","minLength":1},"previous":{"type":"string","minLength":1},"rotateRight":{"type":"string","minLength":1},"zoomIn":{"type":"string","minLength":1},"zoomOut":{"type":"string","minLength":1}},"required":["acknowledgements","goHome","imageUnavailable","next","previous","rotateRight","zoomIn","zoomOut"]}},"required":["options","content"]},"searchFooterPanel":{"type":"object","properties":{"options":{"type":"object","properties":{"elideDetailsTermsCount":{"type":"number"},"elideResultsTermsCount":{"type":"number"},"pageModeEnabled":{"type":"boolean"}},"required":["elideDetailsTermsCount","elideResultsTermsCount","pageModeEnabled"]},"content":{"type":"object","properties":{"clearSearch":{"type":"string","minLength":1},"defaultLabel":{"type":"string","minLength":1},"displaying":{"type":"string","minLength":1},"enterKeyword":{"type":"string","minLength":1},"image":{"type":"string","minLength":1},"imageCaps":{"type":"string","minLength":1},"instanceFound":{"type":"string","minLength":1},"instancesFound":{"type":"string","minLength":1},"nextResult":{"type":"string","minLength":1},"page":{"type":"string","minLength":1},"pageCaps":{"type":"string","minLength":1},"previousResult":{"type":"string","minLength":1},"resultFoundFor":{"type":"string","minLength":1},"resultsFoundFor":{"type":"string","minLength":1},"searchWithin":{"type":"string","minLength":1}},"required":["clearSearch","defaultLabel","displaying","enterKeyword","image","imageCaps","instanceFound","instancesFound","nextResult","page","pageCaps","previousResult","resultFoundFor","resultsFoundFor","searchWithin"]}},"required":["options","content"]},"settingsDialogue":{"type":"object","properties":{"content":{"type":"object","properties":{"locale":{"type":"string","minLength":1},"pagingEnabled":{"type":"string","minLength":1},"preserveViewport":{"type":"string","minLength":1},"title":{"type":"string","minLength":1},"website":{"type":"string","minLength":1}},"required":["locale","pagingEnabled","preserveViewport","title","website"]}},"required":["content"]},"treeViewLeftPanel":{"type":"object","properties":{"options":{"type":"object","properties":{"elideCount":{"type":"number"},"galleryThumbHeight":{"type":"number"},"galleryThumbWidth":{"type":"number"},"oneColThumbHeight":{"type":"number"},"oneColThumbWidth":{"type":"number"},"pageModeEnabled":{"type":"boolean"},"panelAnimationDuration":{"type":"number"},"panelCollapsedWidth":{"type":"number"},"panelExpandedWidth":{"type":"number"},"panelOpen":{"type":"boolean"},"thumbsEnabled":{"type":"boolean"},"thumbsExtraHeight":{"type":"number"},"thumbsImageFadeInDuration":{"type":"number"},"thumbsLoadRange":{"type":"number"},"treeEnabled":{"type":"boolean"},"twoColThumbHeight":{"type":"number"},"twoColThumbWidth":{"type":"number"}},"required":["elideCount","galleryThumbHeight","galleryThumbWidth","oneColThumbHeight","oneColThumbWidth","pageModeEnabled","panelAnimationDuration","panelCollapsedWidth","panelExpandedWidth","panelOpen","thumbsEnabled","thumbsExtraHeight","thumbsImageFadeInDuration","thumbsLoadRange","treeEnabled","twoColThumbHeight","twoColThumbWidth"]},"content":{"type":"object","properties":{"collapse":{"type":"string","minLength":1},"collapseFull":{"type":"string","minLength":1},"expand":{"type":"string","minLength":1},"expandFull":{"type":"string","minLength":1},"index":{"type":"string","minLength":1},"thumbnails":{"type":"string","minLength":1},"title":{"type":"string","minLength":1}},"required":["collapse","collapseFull","expand","expandFull","index","thumbnails","title"]}},"required":["options","content"]},"clickThroughDialogue":{"type":"object","properties":{"content":{"type":"object","properties":{"viewTerms":{"type":"string","minLength":1}},"required":["viewTerms"]}},"required":["content"]}},"required":["dialogue","downloadDialogue","embedDialogue","footerPanel","genericDialogue","helpDialogue","moreInfoRightPanel","pagingHeaderPanel","seadragonCenterPanel","searchFooterPanel","settingsDialogue","treeViewLeftPanel","clickThroughDialogue"]},"localisation":{"type":"object","properties":{"label":{"type":"string","minLength":1},"locales":{"type":"array","uniqueItems":true,"minItems":1,"items":{"required":["name","label"],"properties":{"name":{"type":"string","minLength":1},"label":{"type":"string","minLength":1}}}}},"required":["label","locales"]},"content":{"type":"object","properties":{"canvasIndexOutOfRange":{"type":"string","minLength":1},"degradedResource":{"type":"string","minLength":1}},"required":["canvasIndexOutOfRange","degradedResource"]}},"required":["options","modules","localisation","content"]}

=== UniversalViewer/universalviewer/dist/uv-1.5.3/lib/uv-seadragon-extension.cy-GB.config.json
{"options":{"leftPanelEnabled":true,"minWidthBreakPoint":610,"overrideFullScreen":false,"pagingEnabled":true,"pessimisticAccessControl":false,"preserveViewport":false,"rightPanelEnabled":true,"searchWithinEnabled":true,"theme":"uv-cy-GB-theme"},"modules":{"dialogue":{"content":{"close":"Cau"}},"downloadDialogue":{"options":{"confinedImageSize":1000},"content":{"currentViewAsJpg":"Golwg presennol (jpg)","download":"Lawrlwytho","editSettings":"Golygu'r dewisiadau","entireDocument":"Y Ddogfen Gyfan ({0})","entireFileAsOriginal":"Y ffeil gyfan ({0})","noneAvailable":"Nid oes unrhyw opsiynau lawrlwytho ar gael.","pagingNote":"Dad-ddewiswch 'Arddangos Dwy Dudalen' i weld dewisiadau pellach.","preview":"Rhagolwg","title":"Lawrlwytho","wholeImageHighRes":"Y ddelwedd gyfan o ansawdd uchel ({0})","wholeImageLowResAsJpg":"Y ddelwedd gyfan o ansawdd isel (jpg)"}},"embedDialogue":{"options":{"embedTemplate":"<div class=\"uv\" data-locale=\"{0}\" data-config=\"{1}\" data-uri=\"{2}\" data-sequenceindex=\"{3}\" data-canvasindex=\"{4}\" data-zoom=\"{5}\" data-rotation=\"{6}\" style=\"width:{7}px; height:{8}px; background-color: #000\"></div>\n<script type=\"text/javascript\" id=\"embedUV\" src=\"{9}\"></script><script type=\"text/javascript\">/* wordpress fix */</script>"},"content":{"customSize":"Maint ddewisol","height":"Hyd","instructions":"Er mwyn ymgorffori'r eitem hon ar eich gwefan, cop√Øwch a gosodwch y cod isod:","title":"Ymgorffori","width":"Lled"}},"footerPanel":{"options":{"downloadEnabled":true,"embedEnabled":true,"fullscreenEnabled":true,"minimiseButtons":false},"content":{"download":"Lawrlwytho","embed":"Ymgorffori","exitFullScreen":"Dianc o'r sgrin lawn","fullScreen":"Sgrin lawn"}},"genericDialogue":{"content":{"emptyValue":"rhowch rif","invalidNumber":"Rhowch rif dilys","noMatches":"Dim canlyniad sy'n cyfateb.","ok":"GWELD","pageNotFound":"Nid yw'r eitem yn cynnwys tudalen gyda'r rhif a nodwyd. Ceisiwch cyfnewid y math i 'delwedd'.","refresh":"Ailosod"}},"helpDialogue":{"content":{"text":"testun i'w osod","title":"Cymorth"}},"moreInfoRightPanel":{"options":{"panelAnimationDuration":250,"panelCollapsedWidth":30,"panelExpandedWidth":255,"panelOpen":false,"textLimit":4,"textLimitType":"lines"},"content":{"collapse":"Cuddio Mwy o Wybodaeth","collapseFull":"Cuddio'r Galeri","expand":"Ehangu Fwy o Wybodaeth","expandFull":"Ehangu'r Galeri","holdingText":"Eich modiwl fan hyn!","less":"llai","more":"mwy","noData":"Nid oes data i'w arddangos","title":"Mwy o Wybodaeth"}},"pagingHeaderPanel":{"options":{"localeToggleEnabled":false,"pageModeEnabled":true,"pagingToggleEnabled":true},"content":{"close":"Cau","emptyValue":"Mewnosodwch werth","first":"gyntaf","firstImage":"Delwedd Gyntaf","firstPage":"Tudalen gyntaf","folio":"ffolio","go":"GWELD","help":"Cymorth","image":"Delwedd","last":"Olaf","lastImage":"Delwedd Olaf","lastPage":"Tudalen Olaf","next":"Nesaf","nextImage":"Delwedd Nesaf","nextPage":"Tudalen Nesaf","of":"o {0}","oneUp":"Gweld un dudalen ar y tro","page":"Tudalen","previous":"Blaenorol","previousImage":"Delwedd Flaenorol","previousPage":"Tudalen Flaenorol","settings":"Dewisiadau","twoUp":"Gweld dwy dudalen ar y tro"}},"seadragonCenterPanel":{"options":{"controlsFadeAfterInactive":1500,"controlsFadeDelay":250,"controlsFadeLength":250,"defaultZoomLevel":0,"navigatorPosition":"BOTTOM_RIGHT","pageGap":0.01,"trimAttributionCount":150},"content":{"acknowledgements":"Cydnabyddiaethau","goHome":"Gweld y maint gwreiddiol","imageUnavailable":"Nid oes delwedd ar gael","next":"nesaf","previous":"blaenorol","rotateRight":"Cylchdroi i'r dde","zoomIn":"Closio","zoomOut":"Gwrthglosio"}},"searchFooterPanel":{"options":{"elideDetailsTermsCount":20,"elideResultsTermsCount":5,"pageModeEnabled":true},"content":{"clearSearch":"Clirio bob dewis","defaultLabel":"-","displaying":"Dangos {0} {1} o {2}","enterKeyword":"Mewnosodwch allweddair","image":"delwedd","imageCaps":"delwedd","instanceFound":"Dangos 1 canlyniad ar gyfer '{0}' ","instancesFound":"Dangos {0} canlyniad o '{1}' ","nextResult":"Canlyniad nesaf","page":"tudalen","pageCaps":"tudalen","previousResult":"Canlyniad blaenorol","resultFoundFor":"canlyniad a geir ar gyfer","resultsFoundFor":"canlyniad ar gyfer","searchWithin":"Chwilio tu fewn i:"}},"settingsDialogue":{"content":{"locale":"Iaith","pagingEnabled":"Arddangos dwy dudalen","preserveViewport":"Cadw'r lefel o glosio","title":"Dewisiadau","website":"<a href='https://github.com/universalviewer/universalviewer'>mwy o wybodaeth</a>"}},"treeViewLeftPanel":{"options":{"elideCount":40,"galleryThumbHeight":320,"galleryThumbWidth":200,"oneColThumbHeight":320,"oneColThumbWidth":200,"pageModeEnabled":true,"panelAnimationDuration":250,"panelCollapsedWidth":30,"panelExpandedWidth":255,"panelOpen":true,"thumbsEnabled":true,"thumbsExtraHeight":8,"thumbsImageFadeInDuration":300,"thumbsLoadRange":15,"treeEnabled":true,"twoColThumbHeight":150,"twoColThumbWidth":90},"content":{"collapse":"Cuddio'r Cynnwys","collapseFull":"Cuddio'r Galeri","expand":"Ehangu'r Cynnwys","expandFull":"Ehangu'r Galeri","index":"Mynegai","thumbnails":"Bodluniau","title":"Cynnwys"}},"clickThroughDialogue":{"content":{"viewTerms":"Darllenwch Telerau ac Amodau Llawn"}}},"localisation":{"label":"Cymraeg","locales":[{"name":"cy-GB","label":"Cymraeg"},{"name":"en-GB","label":"English (GB)"}]},"content":{"canvasIndexOutOfRange":"Canfas yn rhy fawr i'w arddangos (ceisiwch eto)","degradedResource":"This image is degraded."}}
